language: go
sudo: false
go:
  - 1.11.x
  - tip

before_install:
  - go mod download

script:
  - go test ./... -coverprofile=coverage.out -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
