language: go
sudo: false
go:
  - 1.11.x

env:
  - GO111MODULE=on

install: true

script:
  - go test ./... -coverprofile=coverage.out -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
